src/components/addresses/Address/index.js
src/components/blockchain/Statistics/VoteStats.js
src/components/markets/MarketOverview.js
src/components/markets/index.js
src/components/network/Nodes.js
src/components/tools/NodeTester/index.js
src/components/wallet/Wizard/index.js
src/routes.js
src/translations/de.js
src/translations/en.js

- translate status messages 
- translate wallet creation wizzard
- small changes and fixes

Late Night Update 05.06.2018 

---

src/components/Accounts.js
src/components/Home/RecentBlocks.js
src/components/Home/RecentTransactions.js
src/components/Home/RecentTransfers.js
src/components/Home/index.js
src/components/Representative/index.js
src/components/common/Paging.js
src/components/network/NodeMap/async.js
src/components/network/Representatives.js
src/components/tools/TransactionViewer/Scanner.js
src/components/tools/TransactionViewer/index.js
src/components/transfer/Receive/ReceiveModal.js
src/components/wallet/Wizard/index.js
src/translations/br.js
src/translations/de.js
src/translations/en.js
src/translations/es.js
src/translations/fa.js
src/translations/fr.js
src/translations/ko.js
src/translations/nl.js
src/translations/zh.js

DevUpdate - Translation - adding new variables

---

src/components/Home/index.js
src/components/addresses/Address/index.js
src/components/blockchain/Transactions.js
src/components/common/Copy.js
src/components/tokens/TokenDetail/index.js
src/translations/br.js
src/translations/de.js
src/translations/en.js
src/translations/es.js
src/translations/fa.js
src/translations/fr.js
src/translations/ko.js
src/translations/nl.js
src/translations/zh.js

- add var
copied_to_clipboard
view_tokens
create_new_wallet
view_super_representatives
vote_for_supre_representatives
Nr_of_Transfers
loading_token
- changing varname:
produced_blocks
token_balances

translationupdate - add var

---

src/components/account/Account.js
src/components/account/ChangeNameModal.js
src/components/blockchain/Block/index.js
src/components/common/Avatar.js
src/components/common/Links.js
src/components/transfer/Send/SendForm.js
src/components/transfer/SendOption.js
src/components/voting/VoteOverview.js
src/components/wallet/Wizard/index.js

fixes #20
fixes #31
fixes #46
fixes #48

Various Improvements

---

src/components/markets/MarketOverview.js
src/components/tokens/Overview/TokenList.js
src/components/wallet/Wizard/index.js
src/styles/main.scss
src/styles/themes/tron.scss

Various visual improvements

---

src/components/blockchain/Statistics/RichList.js
src/components/blockchain/Statistics/index.js
src/components/tokens/Overview/index.js
src/translations/br.js
src/translations/de.js
src/translations/en.js
src/translations/es.js
src/translations/fa.js
src/translations/fr.js
src/translations/ko.js
src/translations/nl.js
src/translations/sv.js
src/translations/zh.js

- add new variables
- review and optimization swedish translation

Translationupdate 10-06-2018

---

src/components/Home/index.js
src/components/account/Account.js
src/components/account/TestNetRequest.js
src/components/dialogs/TestNetWarning.js
src/components/voting/VoteOverview.js
src/reducers/app.js
src/translations/br.js
src/translations/de.js
src/translations/en.js
src/translations/es.js
src/translations/fa.js
src/translations/fr.js
src/translations/index.js
src/translations/ko.js
src/translations/nl.js
src/translations/sv.js
src/translations/tr.js
src/translations/zh.js

- add new variables
- need_min_trx_to_vote_message
- to_much_votes_massage
- votes_remaining_message
- all_votes_are_used_message
- open_wallet_start_voting_message
...

Translation update 10-06-2018-1

---

src/reducers/app.js
src/translations/index.js
src/translations/it.js

- adding the italian translation

[UPD] Translation - add italian translation

---

src/components/ledger/Index.js

Made sure to cleanup listener on 'unmount'.

---

src/components/common/Recaptcha.js

Modified to not change direct state(EOM)

Modified to not change direct state(EOM)

---

src/components/Representative/index.js
src/translations/ar.js
src/translations/br.js
src/translations/cs.js
src/translations/de.js
src/translations/en.js
src/translations/es.js
src/translations/fa.js
src/translations/fr.js
src/translations/it.js
src/translations/ka.js
src/translations/ko.js
src/translations/nl.js
src/translations/no.js
src/translations/pl.js
src/translations/ro.js
src/translations/sv.js
src/translations/tr.js
src/translations/uk.js
src/translations/vi.js
src/translations/zh.js

PR Description
--------------
new/updated translations:
- PL
- SV
new changes/variables:
- "budget_expenses": "Budget Expenses",
- "server_configuration": "Server Configuration",
- "community_plan": "Community Plan",
- "team": "Team",

[UPD] - language extension 

---

src/components/Pages/News.js

Correcting news links for representatives
Fixes #335

Fixing issues #335 - correcting representative links

---

src/components/voting/VoteOverview.js

Fixing voting cancel bug - #97

---

src/components/common/chart.config.js

Fixes line chart x axis label tick alignment

---

src/components/common/Paging.js
src/components/tokens/Overview/index.js
src/styles/main.scss

Visual improvements

---

src/components/blockchain/Statistics/SingleChart.js
src/components/blockchain/Statistics/index.js
src/components/common/LineCharts.js
src/components/common/chart.config.js
src/components/markets/index.js

add '24 Hour Trading Volume' chart

add   ’24 Hour Trading Volume’   chart

---

src/components/account/FreezeBalanceModal.js
src/components/blockchain/Statistics/SingleChart.js
src/components/blockchain/Statistics/index.js
src/components/representatives/Representatives.js

Change translate key

---

src/components/blockchain/Statistics/index.js
src/components/representatives/Representatives.js

Del getPiechat

---

src/translations/es.js
src/translations/ro.js
src/translations/tr.js

PR Description
--------------
- ES
- RO
- TR

[UPD] - Bugfix/Language extension # 33

---

src/components/common/LineCharts.js
src/components/common/RingPieChart.js
src/components/common/chart.config.js

Block producer chart add tooltip formatter

Block producer chart add tooltip formatter

---

src/translations/ar.js
src/translations/br.js
src/translations/cs.js
src/translations/de.js
src/translations/en.js
src/translations/es.js
src/translations/fa.js
src/translations/fr.js
src/translations/it.js
src/translations/ka.js
src/translations/ko.js
src/translations/nl.js
src/translations/no.js
src/translations/pl.js
src/translations/ro.js
src/translations/ru.js
src/translations/sv.js
src/translations/th.js
src/translations/tr.js
src/translations/uk.js
src/translations/vi.js
src/translations/zh.js

PR Description
--------------
ES
ZH
AR  
"confirm_private_key":"Confirm Private Key",
"transfer_confirm_info":"Are you sure you want to transfer"

[UPD] - Bugfix/Language extension # 35

---

src/components/common/chart.config.js

Change piechart color

---

src/hw/ledger/LedgerAccess.jsx

- Add confirm = true in ledger.checkForConnection

Request ledger hardware confirmation on signin
